### ISSUE TITLE
View Transaction History

### ISSUE THREAD

**Issue by Joseleelsuper** [Joseleelsuper/GESPRO_Practica_2_Curso_2024_2025#21]

**Comment by tbf1003** [comment]
how are you planning to structure the transaction data? Are you including filters for date range or transaction type?

**Comment by Joseleelsuper** [comment]
The transaction history is made in order to have some records that the user may want to see.

Answering your question, no. This only Will show de transactions price and date. The user can order his transactions with the bank app of his account.

**Comment by tbf1003** [comment]
Got it! Thanks for explaining.
